# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundCloud' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundCloud
	pod 'Reusable'
	pod 'Alamofire'
	pod 'ObjectMapper'
	pod 'Kingfisher'
	pod 'SpringIndicator'
	pod 'UICircularProgressRing'
end
